[package]
name = "spikes"
version = "0.1.0"
authors = ["Luiz Silveira <zertyz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap = "0.7"
#num = "0.3"
#zkp-mmap-vec = "0.1.0"
#libc = "0.2"
